### ISSUE TITLE
Crash in AutomorphismGroupByInvariants 

### ISSUE THREAD

**Issue by eobr007** [thetensor-space/Auto-Sandbox#11]
G:= PCGroup(\[ 9, -11, 11, 11, 11, 11, -11, 11, 11, 11, 27041107303, 526156886,
395615, 701542524, 527493, 79780153, 79725712 ]);

AutomorphismGroupByInvariants (G)
crashes with error 
In file "/home/eobr007/Stabiliser/Auto-Sandbox/src/isom-test.m", line 271, 
column 11:
>>   LV := L @ piV;
             ^
Runtime error in map application: Element is not in the domain of the map

Indeed L is not in the domain of the map. I believe the source of the error is the following change to the defn of Subgroup in isom-test.m.  The filler might more sensibly be to define Subgroup as the trivial group of the domain -- but IsometryGroup doesn't help! 

 try
          vprint Autotopism, 1 : "Adding exponential of derivations by Brooksbank-Maglione-Wilson.";
//      Subgroup := ExponentiateDerivations(T);
    Subgroup := IsometryGroup(T); // No more ExponentiateDerivations. I Put this in as filler. -Josh
  catch e
        vprint Autotopism, 1 : "Lie algebra methods not fully supported for this tensor";//, e;

**Comment by algeboy** [comment]
The filler was indeed wrong.  It is the right group but not acting on the whole space.  It needs to be padded out with the identity to be a subgroup of the pseudo-isometry group.  I added this and it now works.
