### ISSUE TITLE
der-densor stabilizer

### ISSUE THREAD

**Issue by joshmaglione** [thetensor-space/Auto-Sandbox#9]
There must be a better way to do what I wrote in `src/builds/der-densor.m`. In lines 223 through 228, I do the following.
1. Construct the vector stabilizer, using Magma's `Stabilizer`. 
2. Build a homomorphism from my original matrix group to a different matrix group given by the action on the densor subspace. 
3. Use `@@` on the computed stabilizer to get the stabilizer in my original matrix group. 

@galois60 is there a better way to do what I need in Magma?

**Comment by galois60** [comment]
That seems pretty sensible to me. Which is to say, that's more or less how I would do it. 

Eamonn raised an interesting aspect of this sort of computation, though, that's worth bearing in mind (although it probably won't have much impact here). When you compute a stabilizer, you often end up with many more generators that you need. Then, lifting them––as you are doing here––can become expensive. One can apply ReduceGenerators to your stabilizer before you lift it. I just wrote such an intrinsic and put it in Auto-Sandbox "Util.m" file.

By the way, when you write **@galois60**, are you trying to apply me to something?

**Comment by joshmaglione** [comment]
Hah! Yes, I'm applying you to the post in hopes you turn my ideas into something sensible.

OK that is good to know. I will change the code to reduce the generators soon, or anyone can do it if they want to. Thanks!
